---
- hosts: tag_Name_db_1
  become: yes
  become_method: sudo
  become_user: root
  roles: 
    - common
    - mysql

    
- hosts: tag_Name_web_1
  become: yes
  become_method: sudo
  become_user: root
  roles: 
    - common
    - web
    #- mysql
    - wordpress
  
